export interface Ticket {
    id : string,
    invoice_number : string,
    date_created : string,
    date_ticket_played : string,
    qr_code_digits : string,
    state : string,
    client : string,
    game_id : string,
    game_name : string,
    user_register : string,
    client_cedula : string,
    client_id : string,
    game_start : string,
    game_end : string,
  }
